name: Deploy to Hetzner

on:
  push:
    branches:
      - main 

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.HETZNER_DEPLOY_KEY }}

    - name: Deploy with Deployer
      run: |
        curl -LO https://deployer.org/deployer.phar
        php deployer.phar deploy production
