name: Deploy to Hetzner

on:
  push:
    branches:
      - main 

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy with Deployer
      uses: deployphp/action@v1
      with:
        private-key: ${{ secrets.HETZNER_DEPLOY_KEY }}
        deployer-version: '7.5.12'
        dep: deploy
